version: '3.1'

services:
  master:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - ./db/master/conf:/etc/mysql/conf.d
      - ./db/master/log:/var/log/mysql
    ports:
      - "3306:3306"
  slave:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - ./db/slave/conf:/etc/mysql/conf.d
      - ./db/slave/log:/var/log/mysql
    ports:
      - "3307:3306"

  zookeeper:
    image: 'bitnami/zookeeper:3.9.1'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.6.1'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
  
  cassandra:
    image: cassandra:4.1.3
    ports:
      - 9042:9042

  # zipkin:
  #   image: openzipkin/zipkin-slim
  #   ports:
  #    - 9411:9411