version: '3.1'

services:
 master:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - ./db/master/conf:/etc/mysql/conf.d
      - ./db/master/log:/var/log/mysql
    ports:
      - "3306:3306"

 slave:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - ./db/slave/conf:/etc/mysql/conf.d
      - ./db/slave/log:/var/log/mysql
    ports:
      - "3307:3306"
