spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/chat
      username: root
      password: root
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/chat
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379



jwt:
  secret-key: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
  token-validity-in-sec: 300
  refresh-token-validity-in-sec: 604800

logging.level:
  org.hibernate.SQL: debug

admin:
  ip: 127.0.0.1

cassandra:
  contact-point: 127.0.0.1
  port: 9042
  local-datacenter: datacenter1
  keyspace: chat


